version: '3'
services:
  mysql:
    image: mariadb
    container_name: mariadb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mariadb-data:/var/lib/mysql
volumes:
  mysql-data:
networks:
  default:
    external:
      name: docker-network