version: '3'
services:
  gitlab:
    image: webcenter/activemq
    container_name: activemq
    volumes:
      - activemq-data:/data
      - activemq-log:/var/log/activemq
    ports:
      - '8161:8161'
      - '61616:61616'
      - '61613:61613'
volumes:
  activemq-data:
  activemq-log:
networks:
  default:
    external:
      name: docker-network
