version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
    - '8000:80'
    volumes:
    - .:/usr/share/nginx/html:ro
networks:
  default:
    external:
      name: docker-network
